

export const projects = [
    {
        id: 1,
        slug: "medallion",
        title: "Medallion", 
        desc: "The mission behind Hercegovačka izba and the creation of Medallion.ba was to make a meaningful mark online by bringing attention to a traditional Herzegovinian delicacy known as Ćupter, a sweet that had faded from public memory over hundered of years. Once a cherished part of the region's culinary heritage, Ćupter had become a forgotten treasure, known only to the older generations and rarely seen in modern kitchens or markets. Through this website, the goal was to tell the story of Ćupter—where it comes from, how it's made, and why it deserves a place in today's world. The idea was not only to preserve tradition, but to revive it. By introducing Ćupter to a broader audience—both in Herzegovina and beyond. Hercegovačka izba hopes to inspire a renewed appreciation for authentic, handmade sweets rooted in culture and history. In addition to storytelling and cultural presentation, the client wanted the site to be functional and accessible. A very simple and user-friendly webshop was included, allowing visitors who are curious about Ćupter, or who fondly remember it, to easily purchase it online and experience this unique taste of Herzegovina for themselves.", 
        tech: ["Figma", "PhotoShop", "ReactJS",  "CPanel" ], 
        video: "",
        mainImage: "/cupter.webp",
        gallery: ["/cupter1.webp", "/cupter2.webp", "/cupter3.webp", "/cupter4.webp"],
        imageAlt: "E-commerce website | Online trgovina stranica | Cupter-Medallion.ba",
        color: "#b2ecfe",
        link: "https://medallion.ba/",
        year: 2023,
        client: "Hercegovačka izba"
    }, {
        id: 2,
        slug: "terminbuddy",
        title: "TerminBuddy", 
        desc: "A personal project, terminBuddy is a web platform designed to bring people together through a shared passion for sports and active lifestyles. Whether you're looking for a partner to join your training session, want to find a group for a casual match, or simply wish to discover new sports activities in your area and meet new people, TerminBuddy makes it easy. The website allows users to browse and join existing sports groups or create their own sessions and invite others to participate. It's built with community and accessibility in mind, offering a simple and intuitive interface where players of all skill levels can connect. From football and basketball to tennis or even running groups, TerminBuddy helps users stay active, meet new people, and make the most of their free time. It's not just about finding a match—it's about building a sports community around you. Whether you're new in town, tired of playing solo, or just want to discover who else is out there playing the sport you love, TerminBuddy is your go-to tool for making those connections happen.", 
        tech: ["Figma", "Illustrator", "NextJS" , "Supabase", "Vercel" ], 
        video: "",
        mainImage: "/termin.webp",
        gallery:["/termin1.webp", "/termin2.webp", "/termin3.webp", "/termin4.webp"], 
        imageAlt: "Sports players connecting platform | Platforma za povezivanje igrača za termine | terminbuddy",
        color: "#65C999",
        link: "https://terminbuddy.vercel.app/",
        year: 2024,
        client: "Personal Project"
    },{
        id: 3,
        slug: "unique-by-mirza",
        title: "Unique by Mirza", 
        desc: "The website Unique by Mirza was created with the goal of expanding the reach of a modern barber shop while staying true to its identity, a space where craftsmanship, style, and atmosphere meet. Designed to attract a wider audience, the site puts the spotlight on the skills and creativity of the barbers, allowing potential clients to get a real sense of what makes this salon different. One of the key features of the website is its visual presentation. From clean layouts to high-quality imagery, every element has been carefully designed to reflect the unique vibe of the shop—where tradition meets trend, and every detail matters Visitors can explore a clear and user-friendly price list, offering a transparent look at the available services and making it easy for clients to plan their next visit. Whether you're looking for a sharp haircut, a classic shave, or a complete grooming experience, Unique by Mirza ensures clients know exactly what to expect. At its core, this website is more than just a digital business card. It's a curated online extension of the salon itself, an invitation to step into a place where precision, personality, and professionalism are always in style.", 
        tech: [ "Figma", "NextJS", "Framer-motion", "Vercel" ], 
        video: "",
        mainImage: "/mirza.webp",
        gallery:["/mirza1.webp", "/mirza2.webp", "/mirza3.webp", "/mirza4.webp"],
        imageAlt: "Website Barber shop | Stranica Muškog Frizera | uniquebymirza.com",
        color: "#FC4332",
        link: "https://uniquebymirza.com/",
        year: 2025,
        client: "Mirza H."
    },  
    {
        id: 4,
        slug: "gardenlux",
        title: "In Development", 
        desc: "In development...", 
        tech: ["Figma", "NextJS", "Framer-Motion" ], 
        video: "",
        mainImage: "/mirza.png",
        gallery:["/cupter1.png", "/cupter2.png", "/cupter3.png", "/cupter4.png"], 
        imageAlt: "",
        color: "#65C999",
        link: " ",
        year: "2025",
        client: " "
    },
    {
        id: 5,
        title: "In Development", 
        slug: "schnaufer-montage",
        desc: "In development...", 
        tech: ["Illustrator","Figma", "NextJS", "Framer-Motion" ], 
        video: "",
        mainImage: "/mirza.png",
        gallery:["/cupter1.png", "/cupter2.png", "/cupter3.png", "/cupter4.png"], 
        imageAlt: "",
        color: "",
        link: " ",
        year: "2025",
        client: " "
    },
]